language: minimal
addons:
  apt:
    packages:
    - docker-ce

services:
- docker
install: docker-compose pull --parallel
jobs:
  include:
    - stage: test
      script: bin/validate_cfn
    - stage: deploy_supporting_infra
      script:
        - ./bin/deploy_cfn cfn vpc dev dev
        - ./bin/deploy_cfn cfn bastion dev dev
        - ./bin/deploy_cfn cfn app dev dev
    - stage: build_app
      script:
        - ./bin/app_build_publish dev $TRAVIS_BUILD_NUMBER
    - stage: deploy_app
        - ./bin/update_app $TRAVIS_BUILD_NUMBER
    - stage: deploy_dns_cert
        - ./bin/deploy_cfn cfn dns ci dev
        - ./bin/ensure_cert dev
        - ./bin/add_lb_listeners dev

env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: SeY4ayzD74iZ/Tz/AsyB9B9EVnWyglpwZg+chQ2ABe+1NN3rk7skZPOVmU2Nj41FIc60wp8zu7kFPsEEyvA9K+LcRwUlCp8WeR0LqEFV6kAzgPDXlXZG3ucHazV/Pkbko+NHSiA4QEIsh3JoaUkdjxt2cXC8xIIyjcgiLE4APNiauYNR1uVkY2nQ2wY+VV+aN7zpadIpuyseh+Yr17YY93U2hnMAsfLo3DBboIIgxowcYVsEhuAJ8eTmpb8tRa5AAmSfYoN/unliDwV7Q1/EPB3ySszpuswgbl1K5ltQr8DEvCwNaAqQZoyEnxzThA6ZBftRSj2smXyxcy13wHTX/89Cggp8UsoC1KIE8Xl3KG5ynXp/lYJm7DNf2sTegJ9xbiJ+VbcJs9JxDLhEDAdNvptG+0M3tKt/e15BmnysKq/e2f5yV427d2g6MBMrdAn0BKKBqK0hO5C6p1CZ2aY86cpjZhOEw0XBEWP6ZO/K6JfZL2jVZVCFdcOl7hrVCykjOrjJG+rqiC2H1410+eb8c+wXGa0vgRkn4VPENaSwSqE2XjHbxgInfYE2rDGaNf9bDnugwrhaAVqs7Ibw00cQedCl7DbPUMvTo+eBhqwjmkie5/zG5uFTtKK6euYFk5bVrJm8vUAPATAWRDXA08Zh+X0cRcx/0YlMs1TEbqeza9Y=
  # AWS_SECRET_ACCESS_KEY
  - secure: WOnIACZG4oYFI8lGoge+LYmbGtA+mvioIAWHcEgjGZ7tsml715DhX+2yjxdTpLM5EKD6ITuUtsWybZKrIpp2pJx2d+L1mA/ziI/2taoK6bQXNhzv3sunqDUqokOwHafycMgISdStgDeqXzc+n14gV0Dwd2uw7BaB2HExyTVdkP4/qRMZO51i+7ufUgpqmdV4gFBqA7GCMUsPKj7q11ObZLiAsAt9LdyByA+GuvZNPS9A5OYNqN7qcKNMNqD72u/AU5Kdoqia4tOdeDMU64isiXSCt8pxjh5zJYxo3mlPl7ln881oD1s/o5SH14g4Q1H6zF33LpUVd0cbK+eVS5OLQHpimR3XIZggfSvx5nRcYpfylz4juPd2GxO3nAK2PDwiN413JIl3WLha9yjvTTIcXw+muPHjOpBs4wirZhJZ3VXokAXPl/lWj/ZksBekyZj4iJ8CIXVaNbAFbcnWC7rA34bpQwl0xYAtv/dbYcViGBQr3YkXNYARHznRKMOFCHzqPmh7KUJNGxhPBcfadrp2lO31Tb7QCJTvNytOJqTZ9k60lpG9NliMxX6hbIDzCEX4kPO3eL5BPCZPSMxarq33dJGiOnqxydo1idnlhkn8avLUg6D4OjxZtkCvFKSoSa+ugqYv2NNjn80EegbmhD2oV14pU/A7vi5MR9Dem7Eltcw=

# agent permissions required:
# - be able to trigger rolling-update in AWS/CFN
# - be able to push docker images to ECR repo
