---
version: "3.4"
services:

  sinatra:
    build: .
    working_dir: /app

  stackup:
    image: realestate/stackup:1.4.1
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/app"
    working_dir: /app
    entrypoint: stackup
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2

  gomplate:
    image: hairyhenderson/gomplate:latest
    volumes:
      - ".:/app"
    working_dir: /app
    entrypoint: /gomplate
