---
AWSTemplateFormatVersion:  "2010-09-09"

Parameters:
  AllowedCidrRanges:
    Description: AllowedCidr used to the bastion
    Type: String
  BastionSSHKeyName:
    Description: SSHkey name for the bastion box.
    Type: String
  BastionInstanceType:
    Description: Instance type for bastion ec2 box.
    Type: String
    Default: t2.nano
  EnvironmentName:
    Description: EnvironmentName aka stack identifier
    Type: String
  AllowedCidrRanges:
    Description: AllowedCidr used to the bastion
    Type: String
  BastionSSHKeyName:
    Description: SSHkey name for the bastion box.
    Type: String
  HostedZoneID:
    Description: "hosted zone id for the new sub domain"
    Type: String
  DomainName:
    Description: "domain name want to register"
    Type: String
  DockerVersion:
    Description: docker image tag
    Type: String
    Default: "latest"
  KeyName:
    Description: Application ssh login keypair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: "sinatra"


Resources:
  codeDeployGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: codeDeployGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  CiUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - codeDeployGroup
      UserName: !Sub ${EnvironmentName}-travis-ci
